CREATE TABLE IF NOT EXISTS quests (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    template_key VARCHAR(64) NOT NULL,
    type SMALLINT NOT NULL,
    arg BIGINT NOT NULL DEFAULT 0,
    extra TEXT DEFAULT NULL,
    progress BIGINT NOT NULL DEFAULT 0,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS tickets BIGINT NOT NULL DEFAULT 0;
