ALTER TABLE users
    ADD COLUMN IF NOT EXISTS wheel_resets_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS wheel_spins_this_cycle INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS redeemed_vote_wheel_spin BOOLEAN NOT NULL DEFAULT FALSE;